### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by wz-ml** [mokemokechicken/keras_BEGAN#4]
Great implementation!
Was wondering if I'd be able to use codebits from the project as part of a GAN in a kaggle competition.
If so, I'll be sure to credit you in comments within the project. 
(Also, I really suck at machine learning so this is probably going to be used more for education purposes than anything. xD)
Thanks!

**Comment by mokemokechicken** [comment]
Thank you very much!

I added License.txt(MIT) to this project.
Please use the codes freely!

**Comment by wz-ml** [comment]
Right, thanks!
